### ISSUE TITLE
Create E2E tests to cover core user journeys

### ISSUE THREAD

**Issue by ckawohl-wmde** [wmde/LOSH-Frontend#34]

**Comment by botoxparty** [comment]
The following user journeys are still pending since the merge of e2e tests in #68 

Explore Data:
As a User I can sort my results by columns on the table
As a User I can page through results
As a User I can decide how many rows per a page
As a User I want to filter through my search results so I can narrow down search results
As a User I can filter by licensing scheme or specific licenses
As a User I can filter for certified projects, and specific certifications 
As a User I can filter by data source
As a User I can filter by organisation 

Detail Page:
As a User I want to select a relevant result so I can explore it in more detail.
As a User I can visit external repo
As a User I can report missing data 
As a User I can return to my previous search results

Navbar
As a User the navigation menu will collapse

Contribute Specs:
As a User I want to download the contributor template so that I can add my data to the database

About Page:
As a User I can view the about page

Ecosystem:
As a User I can view the ecosystem page

Get Involved:
As a User I can view the get involved page

**Comment by botoxparty** [comment]
The following scenarios are **not** currently covered by tests:

The following user journeys are still pending since the merge of e2e tests in #68

Explore Data:
As a User I can sort my results by columns on the table
As a User I can page through results (commented out, flaky in the pipeline)
As a User I can filter by licensing scheme or specific licenses
As a User I can filter for certified projects, and specific certifications
As a User I can filter by data source
As a User I can filter by organisation

Detail Page:
As a User I can report missing data

**Comment by ckawohl-wmde** [comment]
Please revisit as low priority

**Comment by ckawohl-wmde** [comment]
Out of scope
